[package]
name = "scip-sys"
version = "0.1.13"
edition = "2021"
description = "Bindings for the C SCIP solver."
repository = "https://github.com/scipopt/scip-sys"
license = "Apache-2.0"
links = "scip"

[features]
build-headers = ["bindgen"]

[build-dependencies]
bindgen = { version = "0.69.4", optional = true }
cc = "1.0.73"
glob = "0.3.1"
zip = { version = "2.1.3" }
tempfile = { version = "3.2" }
zip-extract = { version = "0.1.3" }
cmake = { version = "0.1.50" }
xz = "0.1.0"
tar = "0.4.40"
flate2 = "1.0.30"
autotools = "0.2.7"

[dependencies]
cmake = "0.1.50"
