[package]
name = "russcip"
authors = ["Mohammad Ghannam <mohammad.m.ghannam@gmail.com>"]
description = "Rust interface for SCIP"
license = "Apache-2.0"
repository = "https://github.com/scipopt/russcip"
version = "0.3.4"
edition = "2021"
exclude = ["data/test/*"]

[dependencies]
scip-sys = { path = "../scip-sys" }

[dev-dependencies]
rayon = "1.5.1"

[lints.clippy]
too_many_arguments = "allow"
